eksctl create cluster \
--name prod \
--region us-east-1 \
--nodegroup-name workers \
--node-type t3.medium \
--nodes 1 \
--nodes-min 1 \
--nodes-max 3 \
--ssh-access \
--ssh-public-key eks-dev \
--zones=us-east-1a,us-east-1b \
--managed